# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/sample.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/sample.proto',
  package='asio_sample',
  serialized_pb='\n\x10src/sample.proto\x12\x0b\x61sio_sample\"\xfd\x01\n\x07request\x12/\n\x04type\x18\x01 \x02(\x0e\x32!.asio_sample.request.request_type\x12-\n\x0brequest_get\x18\x15 \x01(\x0b\x32\x18.asio_sample.request.get\x12-\n\x0brequest_set\x18\x16 \x01(\x0b\x32\x18.asio_sample.request.set\x1a\x12\n\x03get\x12\x0b\n\x03key\x18\x01 \x02(\t\x1a!\n\x03set\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\",\n\x0crequest_type\x12\r\n\tGET_VALUE\x10\x01\x12\r\n\tSET_VALUE\x10\x02\"\x19\n\x08response\x12\r\n\x05value\x18\x01 \x02(\t')



_REQUEST_REQUEST_TYPE = _descriptor.EnumDescriptor(
  name='request_type',
  full_name='asio_sample.request.request_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GET_VALUE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_VALUE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=243,
  serialized_end=287,
)


_REQUEST_GET = _descriptor.Descriptor(
  name='get',
  full_name='asio_sample.request.get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='asio_sample.request.get.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=188,
  serialized_end=206,
)

_REQUEST_SET = _descriptor.Descriptor(
  name='set',
  full_name='asio_sample.request.set',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='asio_sample.request.set.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='asio_sample.request.set.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=208,
  serialized_end=241,
)

_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='asio_sample.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='asio_sample.request.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_get', full_name='asio_sample.request.request_get', index=1,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request_set', full_name='asio_sample.request.request_set', index=2,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REQUEST_GET, _REQUEST_SET, ],
  enum_types=[
    _REQUEST_REQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=287,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='asio_sample.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='asio_sample.response.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=289,
  serialized_end=314,
)

_REQUEST_GET.containing_type = _REQUEST;
_REQUEST_SET.containing_type = _REQUEST;
_REQUEST.fields_by_name['type'].enum_type = _REQUEST_REQUEST_TYPE
_REQUEST.fields_by_name['request_get'].message_type = _REQUEST_GET
_REQUEST.fields_by_name['request_set'].message_type = _REQUEST_SET
_REQUEST_REQUEST_TYPE.containing_type = _REQUEST;
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE

class request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class get(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REQUEST_GET

    # @@protoc_insertion_point(class_scope:asio_sample.request.get)

  class set(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REQUEST_SET

    # @@protoc_insertion_point(class_scope:asio_sample.request.set)
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:asio_sample.request)

class response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:asio_sample.response)


# @@protoc_insertion_point(module_scope)
